apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Internal LoadBalancer
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-05b9dc15ec1a44fd9,subnet-08cec1b60364470a0"  # Specify subnets
spec:
  selector:
    app: app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8501
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas:  
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: ecr-service-account
      containers:
      - name: app
        image: 718425808764.dkr.ecr.us-west-2.amazonaws.com/hmkoptimizations:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
