# apiVersion: v1
# kind: Service
# metadata:
#   name: app-service
# spec:
#   selector:
#     app: app
#   ports:
#   - protocol: "TCP"
#     port: 80
#     targetPort: 8501
#   type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: app  # Your app's selector
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the load balancer
      targetPort: 8051  # Port your app is running on within the pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas:  
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: rahilhussain/test:555
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
