apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-private-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-private-app
  template:
    metadata:
      labels:
        app: my-private-app
    spec:
      serviceAccountName: my-ecr-service-account
      containers:
      - name: my-container
        image: 718425808764.dkr.ecr.us-west-2.amazonaws.com/hmkoptimizations:latest
