apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toapp
spec:
  selector:
    matchLabels:
      app: toapp
  replicas:  
  template:
    metadata:
      labels:
        app: toapp
    spec:
      containers:
      - name: toapp
        image: movista/toapp:D.1.1.0
        #image: 718425808764.dkr.ecr.us-west-2.amazonaws.com/hmkoptimizations:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
